__title__ = "opencv-wrapper"
__description__ = "A Python wrapper for OpenCV."
__url__ = "https://github.com/anbergem/opencv_wrapper"
__version__ = "0.2.1"
__author__ = "Andreas Bergem"
__author_email__ = "bergem.andreas@gmail.com"
__license__ = "MIT"
